### ISSUE TITLE
concatMapM not building with coq-master on CI

### ISSUE THREAD

**Issue by jwiegley** [jwiegley/coq-haskell#5]
@palmskog I'm using:
```
Vulcan ~/src/coq-haskell $ coqc --version
The Coq Proof Assistant, version 8.16+alpha
compiled with OCaml 4.12.1
```
and this builds `coq-haskell` just fine. But the GitHub Actions CI build fails for `coq-dev`. Is CI just behind?

https://github.com/jwiegley/coq-haskell/blob/9e1b0bee61b70061477e57ea7991a30ad2a7b2e6/src/Control/Monad.v#L106

**Comment by palmskog** [comment]
@jwiegley the CI uses Docker containers which are rebuilt about once per day for the Coq `master` variants. The latest rebuild was about 6 hours ago (see the `dev` tag): https://hub.docker.com/r/coqorg/coq/tags

So I guess you could wait for 20 hours or something get a PR building with `coq-dev` that passes.

**Comment by jwiegley** [comment]
Actually, it looks like this repo is now green on CI, after we merged your Makefile changes, so we should be good!

**Comment by jwiegley** [comment]
Now I just need to release version 1.1.0 to OPAM.
